# fly.toml app configuration file generated for stayfit-server on 2023-08-29T17:10:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stayfit-server"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
